# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-02 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scanresult',
            fields=[
                ('host', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('staticdetection', models.IntegerField(default=-1)),
                ('phish', models.IntegerField(default=-1)),
                ('download', models.IntegerField(default=-1)),
                ('fake', models.IntegerField(default=-1)),
                ('distort', models.IntegerField(default=-1)),
                ('trojan', models.IntegerField(default=-1)),
                ('totalscore', models.IntegerField(default=-1)),
                ('lastscantime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
