# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-03 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spidey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='lastscantime',
        ),
    ]
