# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-03 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spidey', '0002_remove_scanresult_lastscantime'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='lastscantime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
