# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-03 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spidey', '0003_scanresult_lastscantime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safescanresult',
            fields=[
                ('host', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
